### ISSUE TITLE
Bulma error prevents compilation

### ISSUE THREAD

**Issue by codegard1** [v4iv/gatsby-starter-business#48]
This error occurs when I attempt to run `gatsby develop` after creating a new site from this starter. 

I have tried to troubleshoot this by making changes to `styles.sass` as well as changing the implementation of `gatsby-plugin-sass` in `gatsby-config.js` but it has not resolved. 

```
chris@plunk1:~/grosky1$ gatsby develop

Something is already running at port 8000
✔ Would you like to run the app at another port instead? … yes
success open and validate gatsby-configs - 0.129s
success load plugins - 1.729s
success onPreInit - 0.082s
success initialize cache - 0.011s
success copy gatsby files - 0.068s
success onPreBootstrap - 0.024s
success createSchemaCustomization - 0.054s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.236s
success building schema - 1.080s
info Total nodes: 94, SitePage nodes: 9 (use --verbose for breakdown)
success createPages - 0.156s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.183s
success update schema - 0.116s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.002s
success onPostBootstrap - 0.006s
info bootstrap finished - 7.880s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.854s
success write out requires - 0.084s
success run page queries - 0.056s - 1/1 17.83/s
 ERROR  Failed to compile with 1 errors                                                                4:11:02 PM
⠀
 error  in ./src/assets/sass/styles.sass
⠀
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

$primary-invert: #ffffff
^
      Invalid CSS after "$primary-invert": expected 1 selector or at-rule, was ": #ffffff"
      in /home/chris/grosky1/src/assets/sass/styles.sass (line 2, column 1)
    at runLoaders (/home/chris/grosky1/node_modules/webpack/lib/NormalModule.js:316:20)
    at /home/chris/grosky1/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chris/grosky1/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chris/grosky1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/home/chris/grosky1/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/home/chris/grosky1/node_modules/neo-async/async.js:8069:18)
    at options.error (/home/chris/grosky1/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/cms/cms.js 6:0-36
 @ multi ./node_modules/gatsby-plugin-netlify-cms/cms.js ./node_modules/gatsby-plugin-netlify-cms/cms-identity.js ./src/cms/cms.js
⠀
error Generating development JavaScript bundle failed


$primary-invert: #ffffff
^
      Invalid CSS after "$primary-invert": expected 1 selector or at-rule, was ": #ffffff"
      in /home/chris/grosky1/src/assets/sass/styles.sass (line 2, column 1)
error Generating development JavaScript bundle failed


.social-links
^
      Invalid CSS after ".": expected 1 selector or at-rule, was ".social-links"
      in /home/chris/grosky1/src/components/Share/styles.sass (line 1, column 1)
failed Building development bundle - 9.196s
```

**Comment by v4iv** [comment]
I'll take a look at it.

**Comment by chris1000** [comment]
Has there been any updates on this?

**Comment by v4iv** [comment]
Sorry for the delay @chris1000 was tied up with other things, you can verify and close it
